upstream node_app {
    # 'app' is the name of the Node service in docker-compose
    server app:3000;
}

server {
    listen 80;
    server_name localhost; # Change to your domain if needed

    # Allow file uploads up to 50 Megabytes
    client_max_body_size 500M;

    location / {
        proxy_pass http://node_app;
        proxy_http_version 1.1;
        
        # Standard proxy headers
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        
        # Timeouts (You may also want to increase these for very large file uploads)
        proxy_connect_timeout 1000s;
        proxy_send_timeout 1000s;
        proxy_read_timeout 1000s;
    }
}